### PR TITLE
add highligter of Excption

### PR DESCRIPTION
**Pull request by jindaxia**
http://postimg.org/image/thgnvd7v9/

### CODE REVIEW

**Comment by phil65** [comment]
thanks :)

**Comment by jindaxia** [comment]
actually,i need to highlight the block between "EXCEPTION Thrown" and "-->End of Python script error report<--" 
but i dont know how to do

**Comment by phil65** [comment]
should be pretty easy. will take a look when I find some free minutes.

**Comment by phil65** [comment]
https://github.com/phil65/SublimeKodi/pull/5

**Pull request merged**
