### PR TITLE
Add Mac lxml + Pillow, and move Win/Lin into separate directory.

### PR DESCRIPTION
**Pull request by ghost**
Platform specific libraries for mac and for win/lin are contained in separate directories (lib-mac & lib-winlin), with the correct folder being added to sys.path dependant on the platform. This gives at least basic Mac compatibility, whilst maintaining Win/Lin (hopefully - not tested these platforms ;))

Worth noting that only basic Mac compatibility has been tested atm - the plugin loads, and the syntax highlighting works. There may be other gotcha's to come on Mac (for example, I've already had to modify code to set the home folder on Mac), but I'll do my best to fix them as and when they come up :).

### CODE REVIEW

**Comment by phil65** [comment]
thank you! will test it. You are correct, there are probably some few more occasions which need platform-specific solutions. From a quick glance:
InfoProvider.py -->  get_userdata_folder() method,
 SublimeKodi.py --> KODI_PRESET_PATH,
Utils.py --> get_sublime_path()  (this one works already perhaps)
They should be very easy to fix, would be great if you could take care of that, too. :)

**Comment by phil65** [comment]
...and for info: Today another person popped up in forums who wants to run this in osx, so your efforts will definitely make some other people happy. :)

**Comment by ghost** [comment]
Where exactly are get_userdata_folder() and KODI_PRESET_PATH meant to link to?

OK, I can guess on get_userdata_folder - the userdata folder, right? :) But the KODI_PRESET_PATH?

And good to hear someone else is interested in Mac compatibility :)

**Comment by phil65** [comment]
KODI_PRESET_PATH should point to the default path of a kodi installation on osx, but is just for convience. You don´t need it in case you set the path to the kodi folder manually in the settings file. That setting can also get written by "Set Kodi Folder" from command palette though, and in that case KODI_PRESET_PATH is used as a preset.
(The path to the kodi installation is needed to fetch the core language files.)

get_userdata_folder() should return the kodi userdata folder, correct. :)

**Comment by phil65** [comment]
Thinkin about it, I probably should just remove the PRESET_PATH stuff altogether and better add a proper explanation to the comments of that setting in settings file, including the default paths for different platforms. )

**Comment by ghost** [comment]
The preset path stuff could well cause trouble on Mac - apps are distributed as packages (essentially just folders with a .app extension). So, the default installation location will be ~/Applications/Kodi.app, but within that you've got the app and all it's data. So, the default addons, for example, are at ~/Applications/Kodi.app/Contents/Resources/Kodi/addons - and I'm not quite sure where the core language files are!

At the very least, it's likely that the code that grabs the core language files (assuming I can find said language files, and if you can give me a hint which function in which file it is :)) will need to be Mac specific.

**Comment by phil65** [comment]
hehe you probably don't want to see that specific code, it's a very quick hackjob because of all the  platform / add-on specifics and the new language resource add-ons introduced in Isengard. :)
Do you use Isengard or Helix? For a quick workaround-ish fix you could try copying the core language folder to userdata/addons/

**Comment by phil65** [comment]
...and you should be able to see if it gets picked up correctly by lookin at SublimeText console. Here on my end it shows:

```
Parsing po file /usr/local/share/kodi/addons/resource.language.en_gb/resources/strings.po
```

for example.

**Comment by phil65** [comment]
...and if you have trouble extracting them from the mentioned container. You can find the core language folder here:
https://github.com/xbmc/xbmc/tree/master/addons/resource.language.en_gb

**Comment by phil65** [comment]
tested on both Windows and Linux, seems as if nothing was broken. :) Thx again!

**Comment by ghost** [comment]
I've set it (in the package settings) to ~/Applications/Kodi.app/Contents/Resources/Kodi - that seems to work fine. I'll set the PRESET_PATH to that, so at least it should work out of the box.

**Comment by phil65** [comment]
ok, great.

**Comment by ghost** [comment]
Might want to let me finish updating get_userdata_path/PRESET_PATH before you merge ;)

**Comment by phil65** [comment]
too late :)

**Comment by phil65** [comment]
(sorry for causing additional buttonpresses for another PR :) )

**Pull request merged**
