### PR TITLE
add native language support

### PR DESCRIPTION
**Pull request by jindaxia**
add native language support
@phil65 for review

### CODE REVIEW

**Comment by phil65** [comment]
hehe nice :)

**Comment by phil65** [comment]
@jindaxia perhaps you could also fix the "open log file" for windows?

**Comment by jindaxia** [comment]
i dont know how to get the folder like this 
C:\Users\jindaxia\AppData\Roaming\
with python

**Comment by phil65** [comment]
seems to be easy :)
os.getenv('APPDATA')
http://stackoverflow.com/questions/13184414/easiest-way-to-get-appdata-path-variable-in-python

**Pull request merged**
